### PR TITLE
feat: add typings support

### PR DESCRIPTION
**Pull request by BrunnerLivio**
Adds typings support for this library.

Selection_036

**Related issue**: #3 nestjs/terminus#233

Tested with `@nestjs/terminus`.

### CODE REVIEW

**Comment by Alex-D** [comment]
LGTM, Thank you! :)

**Comment by BrunnerLivio** [comment]
@Alex-D thanks mate! Would you mind publish a new version on npm? It is currently blocking a release of `@nestjs/terminus`. Nonetheless, thank you for this quick contribution!  :)

**Comment by Alex-D** [comment]
I will do that soon :)

**Comment by BrunnerLivio** [comment]
@Alex-D ping :ping_pong:

**Comment by Alex-D** [comment]
Done: 2.1.0 :)

**Pull request merged**
